# Config file for easy deployment to Render

services:
  - type: web
    name: classroom-captioner
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DEEPGRAM_KEY
        sync: false
      - key: DEEPGRAM_PROJECT
        sync: false
      - key: LECTURE_KEY
        sync: false
